### ISSUE TITLE
Implement `HEALTCHECK` in LDH Docker image

### ISSUE THREAD

**Issue by namedgraph** [AtomGraph/LinkedDataHub#170]
This should make it possible to use `depends_on` (`nginx` depends on `linkeddatahub`) [with a condition](https://docs.docker.com/compose/compose-file/05-services/#long-syntax-1) and avoid the custom nginx Docker image:
```yaml
services:
  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
```
